version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: notification_mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
    ports:
      - ${PORT}:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local


# docker exec notification_mysql /usr/bin/mysqldump -u root --password=mauFJcuf5dhRMQrjj --databases notification > db/notification.sql